# Generated by Django 4.2.2 on 2023-07-09 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_recomendation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anime',
            new_name='anime_recomendation',
        ),
    ]
