# Generated by Django 4.2.2 on 2023-07-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_recomendation', '0002_rename_anime_anime_recomendation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='anime_recomendation',
            new_name='anime',
        ),
    ]
