# Generated by Django 4.2.2 on 2023-07-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_recomendation', '0003_rename_anime_recomendation_anime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ani_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='anime',
        ),
    ]
