# Generated by Django 4.2.2 on 2023-07-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_recomendation', '0004_ani_model_delete_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='ani_model',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
