# Generated by Django 4.2.3 on 2023-07-11 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime_recomendation', '0005_ani_model_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='biblio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_recomendation.ani_model')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
